services:
  subtensor:
    build:
      context: .
      dockerfile: Dockerfile.subtensor
    container_name: subtensor_machine
    volumes:
      - ./scripts/localnet.sh:/usr/local/bin/localnet.sh
    ports:
      - "9945:9945"  # Expose port 9945
      - "9946:9946"  # Expose port 9946
      - "30334:30334"  # Expose internal communication port
      - "30335:30335"  # Expose internal communication port
    networks:
      - subtensor_network

  subnet:
    build:
      context: .
      dockerfile: Dockerfile.subnet
    container_name: subnet_machine
    depends_on:
      - subtensor
    networks:
      - subtensor_network
    environment:
      - COLDKEY_PASSWORD=your_coldkey_password
      - HOTKEY_PASSWORD=your_hotkey_password

networks:
  subtensor_network:
    driver: bridge
