version: '3.8'

services:
  validator:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: masa_validator
    volumes:
      - ./wallet:/root/.bittensor/wallets
    environment:
      - COLDKEY_MNEMONIC=${COLDKEY_MNEMONIC}
      - DEVICE=cpu
      - PORT=8091
      - METRICS_PORT=9100
      - ROLE=validator
      - PYTHONUNBUFFERED=1
      - NETWORK=${NETWORK:-test}
      - NETUID=${NETUID:-249}
      - LOGGING_DEBUG=${LOGGING_DEBUG:-true}
      - WALLET_NAME=${WALLET_NAME:-default}
      - WALLET_HOTKEY=${WALLET_HOTKEY:-default}
    ports:
      - "8091:8091"  # Validator API port
      - "9100:9100"  # Metrics port
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  miner:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: masa_miner
    volumes:
      - ./wallet:/root/.bittensor/wallets
    environment:
      - COLDKEY_MNEMONIC=${COLDKEY_MNEMONIC}
      - DEVICE=cpu
      - PORT=8348
      - METRICS_PORT=9357
      - ROLE=miner
      - PYTHONUNBUFFERED=1
      - NETWORK=${NETWORK:-test}
      - NETUID=${NETUID:-249}
      - LOGGING_DEBUG=${LOGGING_DEBUG:-true}
      - WALLET_NAME=${WALLET_NAME:-default}
      - WALLET_HOTKEY=${WALLET_HOTKEY:-default}
    ports:
      - "8348:8348"  # Miner API port
      - "9357:9357"  # Metrics port
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8348/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  prometheus:
    image: prom/prometheus:latest
    profiles: ["monitoring"]
    volumes:
      - ./config/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - validator

  grafana:
    image: grafana/grafana:latest
    profiles: ["monitoring"]
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_LOG_LEVEL=warn
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    profiles: ["monitoring"]
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    profiles: ["monitoring"]
    container_name: masa_portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
      - "8000:8000"  # Required for edge compute features
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/system/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  prometheus_data:
  grafana_data:
  portainer_data:
