name: Docker Build and Publish

on:
  push:
    branches: [ "dev", "test", "main", "dockerize" ]
    paths:
      - 'docker/**'
      - '.github/workflows/docker-publish.yml'
      - '**/*.py'  # This will trigger the workflow when any Python file changes

jobs:
  determine-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      - id: set-matrix
        run: |
          CHANGED=""
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "docker/subtensor/"; then
            CHANGED="$CHANGED\"subtensor\","
          fi
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "docker/subnet/\|\.py$"; then
            CHANGED="$CHANGED\"subnet\","
          fi
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "docker/miner/\|\.py$"; then
            CHANGED="$CHANGED\"miner\","
          fi
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "docker/validator/\|\.py$"; then
            CHANGED="$CHANGED\"validator\","
          fi
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "docker/protocol/\|\.py$"; then
            CHANGED="$CHANGED\"protocol\","
          fi
          CHANGED="[${CHANGED%,}]"
          echo "matrix=$CHANGED" >> $GITHUB_OUTPUT

  build-and-push:
    needs: determine-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{fromJson(needs.determine-changes.outputs.matrix)}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push image
        run: |
          if [ "${{ matrix.image }}" == "subtensor" ]; then
            CONTEXT="./docker/subtensor"
          else
            CONTEXT="."
          fi
          docker build -t ghcr.io/masa-finance/masa-bittensor/${{ matrix.image }}:${{ github.ref_name }} -f docker/${{ matrix.image }}/Dockerfile $CONTEXT
          docker push ghcr.io/masa-finance/masa-bittensor/${{ matrix.image }}:${{ github.ref_name }}

  display-tags:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Display image tags
        run: |
          echo "The following images have been built and pushed:"
          echo "ghcr.io/masa-finance/masa-bittensor/subtensor:${{ github.ref_name }}"
          echo "ghcr.io/masa-finance/masa-bittensor/subnet:${{ github.ref_name }}"
          echo "ghcr.io/masa-finance/masa-bittensor/miner:${{ github.ref_name }}"
          echo "ghcr.io/masa-finance/masa-bittensor/validator:${{ github.ref_name }}"
          echo "ghcr.io/masa-finance/masa-bittensor/protocol:${{ github.ref_name }}"
