name: Docker Build and Publish

on:
  push:
    branches: [ "dev", "test", "main", "dockerize" ]
    paths:
      - 'docker/**'
      - '.github/workflows/docker-publish.yaml'

jobs:
  build-subtensor:
    name: Build and Push Subtensor
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: github.event.head_commit.modified_files && contains(github.event.head_commit.modified_files, 'docker/subtensor/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push Subtensor
        run: |
          docker build -t ghcr.io/masa-finance/masa-bittensor/subtensor:${{ github.ref_name }} -f docker/subtensor/Dockerfile ./docker/subtensor
          docker push ghcr.io/masa-finance/masa-bittensor/subtensor:${{ github.ref_name }}

  build-subnet:
    name: Build and Push Subnet
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: github.event.head_commit.modified_files && contains(github.event.head_commit.modified_files, 'docker/subnet/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push Subnet
        run: |
          docker build -t ghcr.io/masa-finance/masa-bittensor/subnet:${{ github.ref_name }} -f docker/subnet/Dockerfile .
          docker push ghcr.io/masa-finance/masa-bittensor/subnet:${{ github.ref_name }}

  build-miner:
    name: Build and Push Miner
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: github.event.head_commit.modified_files && contains(github.event.head_commit.modified_files, 'docker/miner/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push Miner
        run: |
          docker build -t ghcr.io/masa-finance/masa-bittensor/miner:${{ github.ref_name }} -f docker/miner/Dockerfile .
          docker push ghcr.io/masa-finance/masa-bittensor/miner:${{ github.ref_name }}

  build-validator:
    name: Build and Push Validator
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: github.event.head_commit.modified_files && contains(github.event.head_commit.modified_files, 'docker/validator/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push Validator
        run: |
          docker build -t ghcr.io/masa-finance/masa-bittensor/validator:${{ github.ref_name }} -f docker/validator/Dockerfile .
          docker push ghcr.io/masa-finance/masa-bittensor/validator:${{ github.ref_name }}

  display-tags:
    name: Display Image Tags
    needs: [build-subtensor, build-subnet, build-miner, build-validator]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Display image tags
        run: |
          echo "The following images have been built and pushed:"
          echo "ghcr.io/masa-finance/masa-bittensor/subtensor:${{ github.ref_name }}"
          echo "ghcr.io/masa-finance/masa-bittensor/subnet:${{ github.ref_name }}"
          echo "ghcr.io/masa-finance/masa-bittensor/miner:${{ github.ref_name }}"
          echo "ghcr.io/masa-finance/masa-bittensor/validator:${{ github.ref_name }}"
