name: Docker Build and Publish

on:
  push:
    branches: [ "dev", "test", "main", "dockerize" ]

jobs:
  build-and-push:
    name: Build and Push Docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    environment:
      name: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker images
        run: |
          # Subtensor
          docker build -t ghcr.io/masa-finance/masa-bittensor/subtensor:${{ github.ref_name }} -f docker/subtensor/Dockerfile ./docker/subtensor
          docker push ghcr.io/masa-finance/masa-bittensor/subtensor:${{ github.ref_name }}
          
          # Subnet
          docker build -t ghcr.io/masa-finance/masa-bittensor/subnet:${{ github.ref_name }} -f docker/subnet/Dockerfile .
          docker push ghcr.io/masa-finance/masa-bittensor/subnet:${{ github.ref_name }}
          
          # Miner
          docker build -t ghcr.io/masa-finance/masa-bittensor/miner:${{ github.ref_name }} -f docker/miner/Dockerfile .
          docker push ghcr.io/masa-finance/masa-bittensor/miner:${{ github.ref_name }}
          
          # Validator
          docker build -t ghcr.io/masa-finance/masa-bittensor/validator:${{ github.ref_name }} -f docker/validator/Dockerfile .
          docker push ghcr.io/masa-finance/masa-bittensor/validator:${{ github.ref_name }}

      - name: Display image tags
        run: |
          echo "The following images have been built and pushed:"
          echo "ghcr.io/masa-finance/masa-bittensor/subtensor:${{ github.ref_name }}"
          echo "ghcr.io/masa-finance/masa-bittensor/subnet:${{ github.ref_name }}"
          echo "ghcr.io/masa-finance/masa-bittensor/miner:${{ github.ref_name }}"
          echo "ghcr.io/masa-finance/masa-bittensor/validator:${{ github.ref_name }}"
